version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nodeJsApp
    overwrite: yes
hooks:
  BeforeInstall:
    - location: "echo 'Cleaning folder...' && rm -rf /home/ec2-user/nodeJsApp/*"
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ec2-user
